# Check out https://docs.codemagic.io/yaml/building-a-react-native-app/ for more information
# Please review and update values

workflows:
    react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_mini
    react-native-ios:
        name: React Native iOS
        max_build_duration: 120
        instance_type: mac_mini
